{"level":"error","message":"Login error: KiteConnect is not a constructor","stack":"TypeError: KiteConnect is not a constructor\n    at file:///Users/AH18616/Downloads/zerodhaalgotrade/server/index.js:47:18\n    at Layer.handle [as handle_request] (/Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/index.js:346:12)\n    at next (/Users/AH18616/Downloads/zerodhaalgotrade/node_modules/express/lib/router/index.js:280:10)\n    at /Users/AH18616/Downloads/zerodhaalgotrade/node_modules/body-parser/lib/read.js:137:5\n    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)","timestamp":"2024-12-09T06:13:37.643Z"}
{"data":null,"error_type":"NetworkException","level":"error","message":"Callback error: No response from server with error code: SELF_SIGNED_CERT_IN_CHAIN","timestamp":"2024-12-09T06:15:41.689Z"}
{"data":null,"error_type":"NetworkException","level":"error","message":"Callback error: No response from server with error code: SELF_SIGNED_CERT_IN_CHAIN","timestamp":"2024-12-09T06:15:41.692Z"}
{"data":null,"error_type":"NetworkException","level":"error","message":"Callback error: No response from server with error code: SELF_SIGNED_CERT_IN_CHAIN","timestamp":"2024-12-09T06:45:56.012Z"}
{"data":null,"error_type":"NetworkException","level":"error","message":"Callback error: No response from server with error code: SELF_SIGNED_CERT_IN_CHAIN","timestamp":"2024-12-09T06:45:56.047Z"}
{"data":null,"error_type":"NetworkException","level":"error","message":"Callback error: No response from server with error code: SELF_SIGNED_CERT_IN_CHAIN","timestamp":"2024-12-09T06:51:09.763Z"}
{"data":null,"error_type":"NetworkException","level":"error","message":"Callback error: No response from server with error code: SELF_SIGNED_CERT_IN_CHAIN","timestamp":"2024-12-09T06:51:09.782Z"}
{"data":null,"error_type":"TokenException","level":"error","message":"Callback error: Token is invalid or has expired.","status":"error","timestamp":"2024-12-09T06:59:32.839Z"}
{"data":null,"error_type":"TokenException","level":"error","message":"Callback error: Token is invalid or has expired.","status":"error","timestamp":"2024-12-09T07:07:40.797Z"}
{"data":null,"error_type":"TokenException","level":"error","message":"Callback error: Token is invalid or has expired.","status":"error","timestamp":"2024-12-09T07:13:02.018Z"}
